### ISSUE TITLE
[BUG] Overlapping wall gets rendered differently based on renderer.

### ISSUE THREAD

**Issue by franzmondlichtmann** [ZDoom/gzdoom#2057] opened 2023-04-20 17:56 UTC
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro

### Relevant hardware info

Nvidia RTX 2080 Super, Intel i7-6700K CPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Edge Case: Overlapping wall gets rendered differently in gzdoom based on renderer. Lower wall is lifted into the upper wall.
Other user mentioned, that DSDA-Doom Port would also render an output very similar to Software Renderer in this edge case.

Hardware Renderer:
![HardwareRenderer](https://user-images.githubusercontent.com/105480088/233447659-b862613d-bfb1-4317-a495-e3863e37c43e.png)

Software Renderer:
![SoftwareRenderer](https://user-images.githubusercontent.com/105480088/233447679-cd8d5dde-7904-4251-8dd2-fed75db51f0a.png)

My Map:
[NeuiError.zip](https://github.com/ZDoom/gzdoom/files/11289075/NeuiError.zip)

### Steps to reproduce the behaviour.

1. Start the NeuiError.wad in gzdoom.
2. Look at the wall in question and switch to Hardware Renderer
3. Look at the wall in question and switch to Software Renderer

**Comment by rickytock** [comment] 2023-04-21 21:28
Issue **can** be duplicated on my machine exactly as described using the same .wad file on (presumably) the same build of Ultimate Doom Builder.

GZDoom 4.10.0 and Ultimate Doom Builder 3.0.0.4043 (724bd24)

Operating System: Windows 10 Home 64-bit (10.0, Build 19042)
System Manufacturer: ASUSTeK COMPUTER INC.
System Model: VivoBook_ASUSLaptop
BIOS: X512DA.306 (type: UEFI)
Processor: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 CPUs), ~2.1GHz
Memory: 8192MB RAM
Available OS Memory: 6092MB RAM

Card name: AMD Radeon(TM) Vega 8 Graphics
Manufacturer: Advanced Micro Devices, Inc.
Chip type: AMD Radeon Graphics Processor
Display Memory: 5079 MB
Dedicated Memory: 2033 MB
Shared Memory: 3045 MB
Current Mode: 1920 x 1080 (32 bit) (75Hz)

**Comment by franzmondlichtmann** [comment] 2023-04-22 05:52
I use Ultimated Doom Builder 3.0.0.4043 (724bd24), too

**Comment by biwa** [comment] 2023-04-22 08:11
To clarify, because OP talks about overlapping walls, which isn't really correct:

This happens when the sector's ceiling is below its floor. Apparently in anything (i.e. other ports and GZDoom's software renderer) other than GZDoom's hardware renderer the floor height has precedence when rendering the lower/upper texture. But in GZDoom's hardware renderer the ceiling height seem to have precedence.

Maybe that's also the cause for #2026.

**Comment by coelckers** [comment] 2023-09-16 20:19
fixed in 5f11fd051bc73ca0a9b871fa2cc02dc0b4bfbbec

**Comment by coelckers** [comment] 2023-09-16 20:19
No, it wasn't the cause for #2026, but they were in closely related code.

**Closed by coelckers** 2023-09-16 20:19 UTC
Labels: bug
