### ISSUE TITLE
[BUG] Bad ACS Library leads to silent crash-to-desktop

### ISSUE THREAD

**Issue by edthebat** [ZDoom/gzdoom#1725] opened 2022-08-30 20:38 UTC
### GZDoom version

GZDoom version g4.9pre-204-gf27acfa6b

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

100 Line Massacre (https://www.doomworld.com/forum/topic/128171-100-line-massacre-vanilla-megawad-final-release/) contains an ACS library that is missing the #library directive. This still appears to function as expected, when loaded alone.
However, if any other ACS libraries are loaded beforehand, such as in another mod, the game will silently crash upon loading a map.
Attached is a mod containing a minimal (empty) ACS library to demonstrate.
[acstest.zip](https://github.com/ZDoom/gzdoom/files/9456484/acstest.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load attached test file along with 100 Line Massacre (load order is vital -- test file must be first)
2. Start a New Game
3. Game should silently crash to desktop

**Comment by madame-rachelle** [comment] 2022-09-01 23:56
Yes you're right - we do need those. I will post one for 4.8.2 posthaste.

**Comment by madame-rachelle** [comment] 2022-09-01 23:57
Ooops closed and commented on the wrong issue, my bad, sorry.

**Comment by edthebat** [comment] 2022-09-02 00:07
Arsinikk has been made aware of this issue and fixed 100 Line Massacre. I have created a second test file to run instead to reproduce the issue. As before, load this file after acstest.zip.

[acstest2.zip](https://github.com/ZDoom/gzdoom/files/9474011/acstest2.zip)

I have narrowed down the issue to the SetFont() function. Without it, the crash does not seem to occur.

**Comment by andrikpowell** [comment] 2022-09-05 23:36
This should be fixed now in my WADs (100 Line Massacre, Slotter, Hellcinerator).

What caused the crash, was the lack of `#library "example"` line in the beginning of my ACS scripts.
My WADs have been updated on /idgames with this fix, so this should no longer be an issue.

I think that the crash was entirely my fault since I'm a little new when it comes to ACS scripting.

**Comment by madame-rachelle** [comment] 2022-09-06 00:28
That may well be but ideally GZDoom does not outright crash under such circumstances. We're lucky in this case, a) idgames was slow with the fix, and b) Ed was able to come up with an example, but in the future erasing the erroneous version from existence does not help the port at all.

When the conditions are ripe for a crash they need to be reproducible, ideally.

**Comment by coelckers** [comment] 2022-10-20 16:18
fixed in 1855edba3744d07c76ef5cc0a50a422e9c1ffc76

**Closed by coelckers** 2022-10-20 16:18 UTC
Labels: bug
