### ISSUE TITLE
[BUG] Video intro can't be skipped and input is disabled if you do this

### ISSUE THREAD

**Issue by Zigmund03** [ZDoom/gzdoom#2200] opened 2023-10-04 17:06 UTC
### GZDoom version

GZDoom 4.11.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro

### Relevant hardware info

AMD Ryzen 5 1600, AMD Radeon RX 570

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

So I created an .ivf video file and put it inside my project to play upon startup. Now if I launch GZDoom with my project and while it is loading I spam the escape key, the main menu activates, but the video keeps playing and you are unable to skip it or even navigate the menu. Basically, everything is stuck until the video ends. Only then can you navigate the menu again.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Create an .ivf video file (you can follow [this](https://forum.zdoom.org/viewtopic.php?t=76355) tutorial)
2. Create a .pk3 file that will contain the .ivf and the MAPINFO lump.
3. Launch the .pk3 you created with GZDoom and once it's loading keep pressing the escape button.
4. You should now see the main menu with the .ivf video playing in the background. Notice that you are unable to skip or navigate the menu until the video ends.

**Comment by Zigmund03** [comment] 2023-10-04 17:22
Ah, okay. I did not know it was a known issue. In that case I wish you good luck in finding the root cause for this.

**Comment by coelckers** [comment] 2023-10-25 14:27
closed as duplicate of https://github.com/ZDoom/Raze/issues/174

**Closed by coelckers** 2023-10-25 14:27 UTC
Labels: bug
