### ISSUE TITLE
[BUG]  GZDoom 4.11 ARM Build fails on D_DoAnonStats()

### ISSUE THREAD

**Issue by Eonfge** [ZDoom/gzdoom#2189] opened 2023-09-26 06:53 UTC
### GZDoom version

4.11

### Which game are you running with GZDoom?

None

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### Please describe your specific OS version

Flatpak ARM64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When building GZDoom for ARM64, the linker crashes.

```
/run/build/gzdoom/src/d_main.cpp:3239:(.text+0x85dc): undefined reference to `DumpCPUInfo(CPUInfo const*, bool)'
/usr/lib/gcc/aarch64-unknown-linux-gnu/13.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: src/CMakeFiles/zdoom.dir/d_anonstats.cpp.o: in function `D_DoAnonStats()':
/run/build/gzdoom/src/d_anonstats.cpp:291:(.text+0x4e4): undefined reference to `DumpCPUInfo(CPUInfo const*, bool)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
FB: host_command_exited_cb 3314013 256
]2;flatpak-builder: Cleanup gzdoomError: module gzdoom: Child process exited with code 1
FB: Unmounting read-only fs: fusermount -uz /srv/buildbot/worker/build-aarch64-6/build/.flatpak-builder/rofiles/rofiles-vPb6zJ
```

[Github details](https://github.com/flathub/org.zdoom.GZDoom/pull/59)
[Full log](https://buildbot.flathub.org/#/builders/14/builds/6121/steps/8/logs/stdio)

**Comment by mjr4077au** [comment] 2023-09-26 07:11
Duplicate of #2188.

**Closed by mjr4077au** 2023-09-26 07:11 UTC
Labels: bug
