### ISSUE TITLE
[BUG] If a door closes on top of a weapon, the weapon disappears and is uncollectable

### ISSUE THREAD

**Issue by BillyRayPreachersSon** [ZDoom/gzdoom#2878] opened 2024-12-29 15:28 UTC
### GZDoom version

GZDoom g4.13.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Mac OS

### Please describe your specific OS version

macOS Ventura 13.6

### Relevant hardware info

Apple Mac Mini M2 Pro, 32GB RAM

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I'm playing the [Requiem](https://doomwiki.org/wiki/Requiem) megawad running on top of Doom2. On level 22, there's a yellow door with four chaingunners behind it (on HMP... there may be more on other difficultly levels).

If I open the door and kill all the chaingunners, four weapons are dropped and I can collect them all.

However, if one ore more of those weapons is dropped underneath the door and the door closes, the weapons disappear when the door closes and are therefore uncollectable.

I've seen the same behaviour when playing level 2 of Doom 2, just round the first bend and down the stairs to the left, so it doesn't appear to be confined to the Requiem map. In this case, either the dropped shotguns or clips disappear if the door closes on top of them.

I've attached my `gzdoom.ini` file, as well as a video showing the issue.
[gzdoom.ini.txt](https://github.com/user-attachments/files/18270016/gzdoom.ini.txt)

https://github.com/user-attachments/assets/ec18065e-7396-49b8-8ea2-98644b1e44ee

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Find a map with a door that closes
2. Entice a baddie under the door
3. Kill baddie
4. Wait for the door to close on their chattels
5. Watch their chattels disappear

**Comment by madame-rachelle** [comment] 2024-12-29 16:31
Not a bug, this is vanilla Doom behaviour.

When spawned by chaingunners the weapons get the MF_DROPPED flag which tells the game that they did not originate from the map itself.

Among other things, this causes the objects in question to get crushed by falling ceilings, such as a closing door. Once crushed they are destroyed forever and not retrievable.

**Closed by madame-rachelle** 2024-12-29 16:31 UTC
Labels: bug
