### ISSUE TITLE
[BUG] Savegame corruption triggered by BoA boulder

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [ZDoom/gzdoom#2051] opened 2023-04-16 09:27 UTC
### GZDoom version

g4.11pre-163-g9fbac8f1d

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

(found by @x3003, see https://github.com/Realm667/WolfenDoom/issues/1293)
Savegames that are made after a boulder has moved trigger the "Savegame is from a different level" message when loading. Apparently this only happens after the boulder has stopped. With release GZDoom 4.10.0 the problem does not occur.
The message is in the file ```gzdoom/src/p_saveg.cpp``` on line 954.

Doom II demonstration: [boulder.zip](https://github.com/ZDoom/gzdoom/files/11241737/boulder.zip)

### Steps to reproduce the behaviour.

1. Load ```boulder.zip``` with Doom II on GZDoom g4.11pre-163-g9fbac8f1d.
2. Open Doom II MAP01.
3. ```summon boulder``` and wait until it stops.
4. Save the game.
5. Load the saved game. This fails, and ```Savegame is from a different level``` is being printed to the console.

**Comment by CandiceJoy** [comment] 2023-04-16 10:05
Tried on HEAD, but could not replicate.  Save loaded just fine.

**Comment by Username-N00b-is-not-available** [comment] 2023-04-16 10:57
@CandiceJoy The devbuild is from DRDTeam, but it's I think at least a month old (pre-163). There are no newer Windows builds on DRDTeam. I think they were compiled and posted automatically (daily or several times a week) some years ago, is the automated compiling means unavailable now?
@Talon1024 [has found](https://github.com/Realm667/WolfenDoom/issues/1293#issuecomment-1510244848) that the problem does not occur after https://github.com/ZDoom/gzdoom/commit/15465f07857216807e282e5b64ba913d594af438, so this issue might be closed, crossing out Windows testing for now.

**Comment by Talon1024** [comment] 2023-04-16 17:09
> @Talon1024 [has found](https://github.com/Realm667/WolfenDoom/issues/1293#issuecomment-1510244848) that the problem does not occur after https://github.com/ZDoom/gzdoom/commit/15465f07857216807e282e5b64ba913d594af438

That was just a quick guess, not a finding. I am in the process of testing it now, however.

To download Windows builds for each commit, go to the Actions tab, and click on the commit. Then you can download the builds from under "Artifacts". GitHub removes these artifacts after a certain period of time, so you'll have to download them soon if you want them.

**Comment by Username-N00b-is-not-available** [comment] 2023-04-16 18:02
Thanks everyone!

**Comment by CandiceJoy** [comment] 2023-04-16 19:24
> @CandiceJoy The devbuild is from DRDTeam, but it's I think at least a month old (pre-163). There are no newer Windows builds on DRDTeam. I think they were compiled and posted automatically (daily or several times a week) some years ago, is the automated compiling means unavailable now? @Talon1024 [has found](https://github.com/Realm667/WolfenDoom/issues/1293#issuecomment-1510244848) that the problem does not occur after [15465f0](https://github.com/ZDoom/gzdoom/commit/15465f07857216807e282e5b64ba913d594af438), so this issue might be closed, crossing out Windows testing for now.

DRDTeam was forced to change hosts around that time.  I'm the DRDTeam admin that did the majority of the migration.  Most of the maintainers have access now, but it's possible the Windows one hasn't been re-setup yet.

I'm going to go ahead and close this issue, though, since we know it doesn't happen after a certain commit, that means it was fixed, and we can't fix it in the past xD

**Closed** 2023-04-16 19:24 UTC
Labels: bug

**Comment by x3003** [comment] 2023-04-17 20:37
>I'm going to go ahead and close this issue, though, since we know it doesn't happen after a certain commit, that means it was fixed, and we can't fix it in the past xD

Well, it still would be nice to test it w/ a recent windows build, as not all can/have access to HEAD.
So plz fix the drdteam issue.

**Comment by CandiceJoy** [comment] 2023-04-17 21:27
> > I'm going to go ahead and close this issue, though, since we know it doesn't happen after a certain commit, that means it was fixed, and we can't fix it in the past xD
> 
> Well, it still would be nice to test it w/ a recent windows build, as not all can/have access to HEAD. So plz fix the drdteam issue.

Everyone has access to HEAD.  It was established that it was fixed HEAD, which means the issue is fixed.  We cannot fix issues in the past as we're not time mages, as much as we would often like to be x3
