### ISSUE TITLE
[BUG] Enemies sometimes render incorrectly while dead/alive. especially noticable with crushers,

### ISSUE THREAD

**Issue by XenoJiiva0053** [ZDoom/gzdoom#2740] opened 2024-10-01 18:51 UTC
### GZDoom version

-g4.13pre-144-g326480cb3

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Relevant hardware info

amd ryzen 9 5950x, RTX 4070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Enemies sometimes render in front of crushers or get partially hidden behind walls.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. load level with crusher.
2. get monsters like baron etc to stand in crusher. their heads will render in front of the crusher
3.

### Your configuration

```ini
https://gist.github.com/XenoJiiva0053/cec24e02a3c5e84bdf0e4d0ce7bb6dac
```

### Provide a Log

![20241001121128_1](https://github.com/user-attachments/assets/b40ec861-094f-4c83-8a4c-34685e741f85)

**Comment by madame-rachelle** [comment] 2024-10-03 05:21
Do you have a location where this happens? Preferably a savegame, preferably on a mapset <20 mb with as few mods as possible

**Comment by madame-rachelle** [comment] 2024-10-03 05:22
Oh wait, I just realized, this is software mode. I am not really sure if much can be done here, to be quite honest.

**Comment by XenoJiiva0053** [comment] 2024-10-03 16:51
After asking around in the discord we figured out it was caused by true color sw renderer

**Comment by madame-rachelle** [comment] 2024-10-08 08:09
This is not a bug as was explained to you. Sprites draw out of their boundaries in the Doom engine, this is something that is not easily done in the hardware renderer. There are some issues with this, in particular that slices of walls and floors can clip through said sprites, but this is not something we can fix, so I am going to go ahead and close this.

**Closed by madame-rachelle** 2024-10-08 08:09 UTC
Labels: bug
