### ISSUE TITLE
[BUG] msglevel applies to console messages as well

### ISSUE THREAD

**Issue by OrdinaryMagician** [ZDoom/gzdoom#1913] opened 2023-01-04 10:43 UTC
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The `msg` cvar (aliased to `msglevel` in the C++ side) is described as filtering hud messages by importance, but it seems that it's applied unconditionally even in the console itself.

### Steps to reproduce the behaviour.

1. Set "minimum message level" to "critical messages" (the highest value)
2. Pick up a bunch of items, no item messages will appear on the hud, as expected
3. Open the console, the item messages won't be there either

**Comment by OrdinaryMagician** [comment] 2023-01-04 10:48
Furthermore, this quirk of the cvar has helped me notice that various PRINT_NONOTIFY messages also could use being OR'd with PRINT_HIGH, since otherwise this cvar will also hide them entirely. It's especially important because this includes traces from vm aborts. People could be unintentionally filtering them and be confused by the lack of error messages.

**Comment by CandiceJoy** [comment] 2023-01-24 19:26
Was this addressed?

**Comment by OrdinaryMagician** [comment] 2023-01-24 21:26
Not really. I only did the changes to error messages so they wouldn't get filtered, but there's still the discrepancy that message level affects both the hud and console.

**Comment by coelckers** [comment] 2023-09-15 20:00
duplicate of a fixed bug

**Closed by coelckers** 2023-09-15 20:00 UTC
Labels: bug
