### ISSUE TITLE
Scroll bar on iwad selection menu

### ISSUE THREAD

**Issue by DoubleAgentDave** [ZDoom/gzdoom#1451] opened 2021-08-11 14:50 UTC
I'm not sure who uses the iwad selection menu, but it pops up sometimes when I use gzdoom and forget to turn it off. My collection of iwads is pretty huge now and the iwad selection menu doesn't fit on the screen and due to it's construction won't resize to smaller than the number of iwads. If you could add a scrollbar to the menu so that it's resizable and usable for me again that would be great.
I'm guessing this is a pretty low priority though.
Thanks!

**Comment by DoubleAgentDave** [comment] 2021-08-11 16:04
At the moment it's on arch with XFCE. 

But I can test it on an old version of ubuntu (with unity or gnome, i can't remember) and windows if you like?

**Comment by alexey-lysiuk** [comment] 2021-08-11 19:02
I'm pretty sure that it’s an issue with GTK based IWAD picker.

**Comment by Gaerzi** [comment] 2021-08-12 08:38
No need to test on Windows, this version of the box has had a scrollbar since forever. You can even see it on the screenshot in [the ZDoom Wiki article about it](https://zdoom.org/wiki/IWAD_selection_box).

**Comment by Architector4** [comment] 2021-09-10 11:11
I can confirm on Arch Linux and with gzdoom recently built from git. The menu can be resized to be made bigger, but its minimal size insists to keep all entries visible. I imagine that having more IWADs than screen height allows would make this menu a chore to use.

![big IWAD menu](https://user-images.githubusercontent.com/23612841/132844875-a8f05f37-adf5-4b68-966a-83cab45baf25.png)

**Comment by Architector4** [comment] 2021-09-10 11:11
As a possible workaround, you can try running gzdoom as `GDK_DPI_SCALE=0.5 gzdoom`

The environment variable tells GTK to scale all text half as small, which makes it less readable, but ends up making the entire menu a bit smaller, which may help.

You could also try messing with GTK theming to reduce margins and such as much as possible, but I'd rather just ask for a scrollbar.

**Comment by DoubleAgentDave** [comment] 2021-09-10 14:47
That works as a workaround yeah. I don't really use the menu a lot mainly as I use zdl or something most of the time, I just felt I ought to leave a bug report.

![screenshot1](https://user-images.githubusercontent.com/47922792/132872374-3ec7a364-c691-4fc1-a487-722fa808d3a5.png)
![screenshot2](https://user-images.githubusercontent.com/47922792/132872399-d4328237-ea3e-4016-a903-76199b8b44e5.png)

**Comment by arrowgent** [comment] 2021-09-27 00:20
my list was getting pretty long, but not THAT long.   good find

now.... someone with GTK experience could add the scrollbar and determine window height
maybe call the desktop resolution (eg 1920x1080) and use 1080/2 to use for the GTK window height.  set it in variable stone so it doesnt have issues with too small or too big on different resolution sizes.

**Comment by vanessakindell** [comment] 2023-01-28 20:39
I'm also having this problem. My list of iwads goes off the screen.

**Comment by CandiceJoy** [comment] 2023-01-28 20:51
Can someone try with HEAD, either by building it themselves or by using my dev build? [https://devbuilds.drdteam.org/gzdoom-linux/](https://devbuilds.drdteam.org/gzdoom-linux/) PR #1859 wasn’t in until after 4.10.

**Comment by madame-rachelle** [comment] 2023-01-29 01:56
Problem still exists.
![image](https://user-images.githubusercontent.com/18584402/215300085-7785bb96-f307-4913-aeec-03d5f5e25705.png)

**Comment by madame-rachelle** [comment] 2023-01-29 01:58
Note that with normal scaling that goes completely off the screen.

**Comment by CandiceJoy** [comment] 2023-01-29 08:03
Fixed in #1979

**Closed** 2023-01-29 09:14 UTC
Labels: bug, OS specific, tech issue
