### ISSUE TITLE
[BUG] SW Renderer - Scrolling linedefs stop scrolling ~15 minutes after starting a map

### ISSUE THREAD

**Issue by mykola-ambar** [ZDoom/gzdoom#1848] opened 2022-11-26 13:55 UTC
### GZDoom version

4.9.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using the software renderer (both paletted and truecolor), scrolling textures stop scrolling after ~15 minutes of in-game time. 

This happens on 4.9.0, but does NOT happen on 4.8.2, so the bug was probably introduced somewhere between those two versions.

This bug does NOT affect the hardware renderer, only the software (carmack) renderers.

### Steps to reproduce the behaviour.

1. Start up GZDoom
2. Go to Options -> Video mode, set Renderer Mode to Doom Software Renderer or (Truecolor Renderer)
3. Warp to MAP28 of Doom 2 (for ease of demonstration)
4. Type `warp -606 -2962` in the console
5. Look at the scrolling texture for ~15 minutes of in-game time (can be sped up by setting `i_timescale` to `100`)
6. The scrolling textures stop scrolling

**Comment by coelckers** [comment] 2023-09-15 18:57
Duplicate of something that got fixed already.

**Closed by coelckers** 2023-09-15 18:57 UTC
Labels: bug
