### ISSUE TITLE
[BUG] GAMEINFO LOAD does not follow documented behavior

### ISSUE THREAD

**Issue by jstebbins** [ZDoom/gzdoom#2011] opened 2023-02-22 01:55 UTC
### GZDoom version

4.10

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Fedora 37

### Relevant hardware info

NA

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The GAMEINFO wiki (https://zdoom.org/wiki/GAMEINFO) says the LOAD option behaves as follows
> ZDoom will automatically load the listed files, if it finds them. It will look first in the same directory as the file containing the GAMEINFO lump, and then in the current working directory.

GZDoom is failing to find the files listed *in the same directory as the file containing the GAMEINFO lump*.

I did a little investigation and found that the code that implements the above (in d_main.cpp)  is looking for a '/' in the filename containing the gameinfo lump. If found, it will search the directory before the '/'. But the "filename" contains a ':' instead. After digging a little deeper I found the ':' is substituted because the file has been marked with the LUMPF_EMBEDDED flag. It appears to me that all files in a directory will be flagged this way.

I'm not familiar enough with the inner working of the code to know what would happen if files in a directory were *not* marked embedded. Or perhaps the code that implements loading should simply also look for a ':" in the name (this is far simpler).

I hacked in the latter and it works for my simple test case. But I don't know what side effects there may be. To summarize the hack
- Add check for ':'
- fix checkpath variable to include '/' since the filename may not include it
- change FileExists test to DirEntryExists (my load objects are subdirectories)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Create a directory ('test' for this example) with a pk3 archive containing a mod
2. Create test/GAMEINFO.txt containing a LOAD directive to load the pk3
3. Run gzdoom -file test, the pk3 will fail to load

**Comment by CandiceJoy** [comment] 2023-02-22 02:01
If you're loading a pk3 anyway, why not just load it directly?

**Comment by jstebbins** [comment] 2023-02-22 02:12
If you read the full description, you will see I *am not* just loading pk3s. There are numerous use cases for the documented behavior of GAMEINFO LOAD. That is just an easily reproducible test example.

**Comment by CandiceJoy** [comment] 2023-02-22 02:20
Well, I tried to reproduce it via your instructions and it loads the pk3 just fine, so :P

**Comment by jstebbins** [comment] 2023-02-22 02:25
Ugh! I could have sworn I tested that specific case.  What I was actually doing is using wadext to extract a wad to a directory. Then use GAMEINFO.txt to LOAD that directory.

**Comment by CandiceJoy** [comment] 2023-02-22 02:33
That works for me as well, albeit with scrambled textures; granted, I'm using a custom build of zwadconv that could easily be the culprit on the textures x3

**Comment by jstebbins** [comment] 2023-02-22 02:38
To be sure we are on the same page:
1. Create directory test
2. cd test
3. wadext some.wad (only directory "some" is in directory "test")
4. create GAMEINFO.txt in directory "test" with 'LOAD="some"'
5. cd ..
6. gzdoom -file test

For me this fails to load the mod that has been unpacked into the directory "test/some"

**Comment by CandiceJoy** [comment] 2023-02-22 02:43
Ahhh, I was running wadconv not wadext.  Ugh.  Is wadext available for mac?  I don't have time to build it atm.

**Comment by jstebbins** [comment] 2023-02-22 02:44
I don't know. Just built it myself today. No biggie if you wish to take this up at another time.

**Comment by CandiceJoy** [comment] 2023-02-22 03:44
I've tried with wadext as well, it still works just fine.  I cannot reproduce this.  Have you tried loading the extracted wad's folder directly?  

Create directory test
cd test
wadext some.wad (only directory "some" is in directory "test")
gzdoom -file some

**Comment by jstebbins** [comment] 2023-02-22 23:28
Yeah, I don't know how it is working for you. I've stepped through this carefully in gdb with a couple different scenarios that are failing. Each is slightly different with slightly different failure modes.

1. Directory "test" with GAMEINFO.txt and subdirectory "some" containing unpacked wad
- GAMEINFO.txt has LOAD="some". 
- ParseGameInfo gets called with fn="test/". 
- It creates checkpath="test/some".
- It calls FileExists(checkpath) which fails because "test/some" is a directory and not a file. 
- Because that test fails  it calls D_AddFile with sc.String="some" instead of with checkpath="test/some". 
- D_AddFile fails with message "Can't open directory 'some'". 
2. Directory "test" with GAME.WAD and subdirectory "some" containing unpacked wad
- GAME.WAD contains only a GAMEINFO lump with LOAD="some". 
- ParseGameInfo gets called with fn="ttt:GAME.WAD". 
- fn has no '/' so lastSlash = NULL and checkpath = sc.String = "some". 
- FileExists fails because "some" is not in the current working directory. 
- D_AddFile gets called with sc.String="some" and fails with message "Can't open directory 'some'".

Perhaps FileExists has a different behavior on your platform? That would explain why scenario 1 above might be working for you.

**Comment by CandiceJoy** [comment] 2023-02-23 00:09
Is it possible that this behaviour is fixed in HEAD?  As a developer, I'm running a custom-compiled version of HEAD.  (If for whatever reason it works in HEAD, it'll be fixed in an upcoming release and we can close the issue ^_^)

**Comment by jstebbins** [comment] 2023-02-23 01:03
The gdb walkthrough above is from HEAD as of a few days ago. I just pulled the latest and still same behavior.

**Comment by CandiceJoy** [comment] 2023-02-23 01:49
LOAD is only designed to work on files, not directories.  That'd be why.

**Comment by jstebbins** [comment] 2023-02-23 02:47
OK. Seems like an odd limitation since loading directories is supported on the command line. It's a one line change to add this support to LOAD.

Scenario 2 above also fails if "some" is a file "some.pk3". As you stated earlier, loading a single pk3 through LOAD is kind of silly. But I've seen mods composed of multiple pk3s and it would be convenient to be able to automatically load all files for such mods.

**Comment by CandiceJoy** [comment] 2023-02-23 02:51
Well, the documentation even says files throughout, it doesn't mention being able to load directories x3  This could be added, of course, but I suspect nobody cares enough to.  Are you interested in PRing it? x3

**Comment by jstebbins** [comment] 2023-02-23 02:54
Sure. I'll submit 2 PRs. One for the directory enhancement.  Another for scenario 2 above. That one may draw more scrutiny, but it would actually be "fixing" something that should work according to the documentation.

**Closed** 2023-09-16 08:52 UTC
Labels: enhancement
