### ISSUE TITLE
[BUG] Calling `EventHandler.Find()` from weapon states sometimes returns null when dying and reloading a save

### ISSUE THREAD

**Issue by Magdiel012** [ZDoom/gzdoom#1911] opened 2023-01-02 18:41 UTC
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Home

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In the very specific circumstance where all weapons held by the player call `EventHandler.Find()` from the first frame of the first state sequence they enter, the method may return null when reloading a save after dying. This does not occur if there is any held weapon that does not call the method from its very first frame, or when reloading a save in any other circumstance.

### Steps to reproduce the behaviour.

Attached is a reproduction project to demonstrate the behavior, made to be run with Doom 2. It simply starts the player off with a pistol that tries to get a reference to an event handler and print its class's name to the console in the first frame of its Select state sequence. Following the steps below should cause the VM to abort from trying to read from a null pointer.

[repro.zip](https://github.com/ZDoom/gzdoom/files/10333106/repro.zip)

From the repro mod:
1. Start a new game.
2. Create a save.
3. Die in the game (dying from taking damage or using the `kill` command makes no difference).
4. Try to reload your save by using the interaction key once dead.

The VM should now abort.

### Your configuration

```ini
N/A
```

### Provide a Log

(Not sure where, or even if, GZDoom dumps VM abort logs to be honest.)

**Comment by Blue-Shadow** [comment] 2023-01-03 01:07
Doing stuff in the first state of the Select state sequence isn't safe (well, apart from things like raising the weapon). This is something I had experienced in the past myself. There was also [another bug report](https://forum.zdoom.org/viewtopic.php?t=73433) where the reporter had experienced some weird behavior stemming from doing things in the first state of the Select state sequence.

**Comment by Player701** [comment] 2023-01-03 07:33
The real problem is not that ```EventHandler.Find``` returns null, but that it does so _only sometimes_ and _under specific conditions_ (when reloading a save file after player's death). For example, starting a new game after dying (either via menu or by pressing the use key without having saved beforehand) or loading a save while alive will not lead to this happening. IMO, this inconsistency should be fixed - either return null always or never.

There's also the issue that the behavior of a saved game somehow depends on the events that happened in the game before it - it's what lead me to think that something wasn't right in the first place.

**Comment by prof-hastig** [comment] 2023-09-14 08:07
I just had a quick look at the code. The cause of your problems is that the weapon's select state gets set before the game is fully up and running, that includes setting up the event handlers.

The select state really isn't a safe place to retrieve these things and from the looks of it this is a design issue so deep that fixing it is not possible. I think you can imagine that swapping actions around in this code will cause a long list of follow-up problems.

**Comment by coelckers** [comment] 2023-09-14 14:58
This one's definitely unfixable. Do not use the Select and Deselect state for ANYTHING but raising or lowering the weapon, it's not going to end well...

**Closed by coelckers** 2023-09-14 14:58 UTC
Labels: bug
