### ISSUE TITLE
[BUG] gzdoom does not load a save at the start of a network game

### ISSUE THREAD

**Issue by Mr-M818** [ZDoom/gzdoom#1648] opened 2022-06-25 02:54 UTC
### GZDoom version

gzdoom-4-8-0-Windows-64bit, gzdoom-4-1-3, gzdoom-4-7-1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro

### Relevant hardware info

AMD Ryzen 7 3700X 8-Core Processor 3.59 GHz, 32,0 GB RAM, AMD Radeon R9 290

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

i can't get gzdoom to load a mulitplayer save at a starting netgame.
im using the stand-alone wad: the adventures of square 
im letting everyone join with a batch file i made to my port forwarded server
but every try to use my file:
for me: square.exe -host 2 +load save1 
for them: square.exe -join ----ip--- +load save1
it says it cannot load in a netgame
and for some reason it fails loading a E1M1 map but there are no maps with M1 
the map in the save is E1A5
--
it does not work with doom2 either with the "newes" gzdoom-4-8-0-Windows-64bit

### Steps to reproduce the behaviour.

start gzdoom with -host 2 +load save1
start gzdoom with -join ___.___.___.___ +load save1
----
for "the adventures of square" i used
for the host (me):
square.exe -host 2 -load save2
for other players (my friends):
square.exe -join [my ip adress] +load save2

### Your configuration

```ini
<script src="https://gist.github.com/Mr-M818/e52cfd150bf49f9b53ca28d7030e1d5a.js"></script>
```

### Provide a Log

<script src="https://gist.github.com/Mr-M818/170c794a352f1bc7b86c6cfa8adb3ac5.js"></script>

**Comment by nashmuhandes** [comment] 2022-07-12 06:36
The proper command line to load a save game is `-loadgame <name_of_save>`.

Not `+load`. Or `+loadgame`. It is precisely `-loadgame`.

**Comment by madame-rachelle** [comment] 2022-07-28 07:31
You also will need to use a full or relative path. On Windows that means adding "save/" to the beginning of the name.

I'm not closing this because it could still be considered a regression considering how misleading this is.

**Comment by Mr-M818** [comment] 2022-07-30 07:19
true, it is confusing that save works but load need a different command 
i could turn it into a feature request that load could do something like
freeze multiplayer and check if everyone can load the save

**Comment by Mr-M818** [comment] 2022-07-30 10:08
the "bug" could be fixed by replacing the text or adding something like this to it, ingame: "try using -loadgame <name_of_save> at netgame start"
at failed netgame in console: " invalid command use -loadgame instead"
not sure if the E1M1 text could be changed too
it was confusing to check the save on "the adventures of square" mod since the the mod does not use the names E#M# but E#A#

**Closed** 2022-10-20 17:12 UTC
Labels: bug
