### ISSUE TITLE
[BUG] Multi-player: host opens windows before all players are connected - bad with fullscreen

### ISSUE THREAD

**Issue by lhofhansl** [ZDoom/gzdoom#2643] opened 2024-07-27 15:58 UTC
### GZDoom version

4.12.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Fedora 39

### Relevant hardware info

Intel

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The application windows opens before all players are connected.
This is especially a problem in **fullscreen mode**.

The first time I thought gzdoom had crashed (or became unresponsive).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. set full screen mode
2. start with -host 2
3. notice that the entire screen seems frozen
(because the application window has already opened and is full screen.)

This seems new with 4.12.x

### Your configuration

```ini
fullscreen enabled
```

**Comment by jontrulson** [comment] 2024-07-28 23:37
FWIW, on Ubuntu 22.04, I see the same behavior with 4.12.2 (was previously running 4.7).

Last lines I see in the terminal as the game is starting (I am the host), is:
```
...
I_InitSound: Initializing OpenAL
  Opened device JACK Default
  EFX enabled
...
```

After that, I see nothing until the second player joins (only playing in 2 player coop mode).  Also, In this state, I cannot hit 'Q' to quit like I used to be able to do in previous versions.  I have to login remotely and kill it.

**Comment by RicardoLuis0** [comment] 2024-07-29 00:04
i think this is from the launcher UI refresh? but there are big changes coming to networking, so it will probably be fixed only then

**Comment by jontrulson** [comment] 2024-07-29 00:07
Well I do everything on the command line, so not using any kind of GUI launcher...

**Comment by jontrulson** [comment] 2024-07-29 00:11
I think the OP is correct, gzdoom creates a window after the 'EFX Enabled' line I see:

```
Using video driver x11
Number of detected displays 4 .
Creating window [2560x1551] on adapter 0
```

Those are the lines I see after the 'EFX Enabled' line I quoted above - though I never see anything after that line in the terminal until I exit the games.

I also run in fullscreen, so that whole monitor is unusable ("frozen") until either a player joins, or I kill the game remotely.

**Comment by RicardoLuis0** [comment] 2024-07-29 01:56
> Well I do everything on the command line, so not using any kind of GUI launcher...

the old launcher handled the netgame connection window as well

**Comment by Boondorl** [comment] 2024-10-01 23:03
That was from a rework to how the start screen is handled (the console is no longer displayed but instead it launches into fullscreen immediately). The issue seems to be that this case wasn't taken into account whatsoever so while it launches the application immediately, it then has to halt executing for the network window. Frankly this is a bad regression that should be addressed sooner rather than later because I don't like my monitor getting bricked while trying to host/join a game.

**Comment by nashmuhandes** [comment] 2024-10-01 23:19
Fixed with https://github.com/ZDoom/gzdoom/commit/f0ff2736203506b4a0c1502ddbf95ba1766d28ef

**Closed by nashmuhandes** 2024-10-01 23:19 UTC
Labels: bug
