### ISSUE TITLE
[BUG] Loading WAD as dir with `-file DIR` do not work while packed DIR.zip/.pk3 works

### ISSUE THREAD

**Issue by vsonnier** [ZDoom/gzdoom#2319] opened 2023-12-23 09:43 UTC
### GZDoom version

4.12 dev build https://github.com/ZDoom/gzdoom/commit/97c04357f16759cfc6a94a0570e2df3af6a58644 

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

x64 Home 23H2

### Relevant hardware info

Nvidia RTX 4070 run with Vulkan

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Loading a WAD "as a directory" with the `-file` argument with complex sub-wads and resources still do not work (even after the lastest File system fixes), while the equivalent packed as .zip or .pk3 load properly.

Such structure can happen with Brutal Doom derivatives for instance.

This makes developpement on such versions quite cumbersome, forcing to pack the resources first into .zip to be able to run the wad. 

This works with GZDoom v4.11.3 release.

### Steps to reproduce the behaviour.

Use the following reproducer ZIP:
[BDBE_test.zip](https://github.com/ZDoom/gzdoom/files/13758574/BDBE_test.zip)

1. Try to load with command line `-config gzdoom-Normal.ini -file D:\xxxxxxxx\BDBE_test.zip` => OK
2. Unzip into BDBE_test dir, such as we have the following structure : 

```c
BDBE_test/BESounds.wad, 
BDBE_test/MAPS/TITLEMAP.wad...etc. 
```
3. Try to load with command line `-config gzdoom-Normal.ini -file D:\xxxxxxxx\BDBE_test`  => The WAD do not load, with unfound resources: (GZDoom console output)
 
```c
G_ParseMapInfo: Load map definitions.
Script error, "D:/xxxxxxxx/BDBE_test/:mapinfo" line 4:
Unknown sound "PTITLE"
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
script parsing took 360.51 ms
R_Init: Init Doom refresh subsystem.
DecalLibrary: Load decals.
M_Init: Init menus.

Execution could not continue.

Script error, "D:/xxxxxx/BDBE_test/:xhairs.wad" line 1:
SC_GetNumber: Bad numeric constant "PWAD^".
```

### Your configuration

[gzdoom-Normal.zip](https://github.com/ZDoom/gzdoom/files/13758638/gzdoom-Normal.zip)

**Comment by vs-shirokii** [comment] 2023-12-23 12:56
Confirming that directories don't work with sub-directories, primarily with `filter/`, reproduction:

* Latest `master` branch
* Here's a [RelWithDebInfo.zip](https://github.com/ZDoom/gzdoom/files/13759088/RelWithDebInfo.zip), that contains:
    * `test.zip` -- zip-archive with filter for ultimate doom with replacing titlepic with plutonia one (for test)
    * `testdir` -- has the same contents as zip, but not as a zip-archive but a plain directory
* Launch as `Doom 1 Ultimate` with args:
    1. `gzdoom.exe -file test.zip` -- as expected, plutonia titlepic appears in the main menu
    1. `gzdoom.exe -file testdir` -- bug, plutonia titlepic is ignored, and the default main menu titlepic is shown
    
I think it's something related to file `namespaces`: e.g. when loading a directory, files under `filter/<>/graphics` are not marked as `ns_graphics` but as `-1`

**Comment by vs-shirokii** [comment] 2023-12-23 13:00
Findings:

There are checks here, if a filename starts with some set of characters, then assume a namespace.
 https://github.com/ZDoom/gzdoom/blob/c05d6224ba0ae9e218036030744b3bd2f44d9c47/src/common/filesystem/source/filesystem.cpp#L138

If, for example, to change `!substr(LongName, "graphics/, 9)` to `strstr(LongName, "graphics/")`, then directories would work -- but of course, this ignores filters and not the intended fix.

**Comment by vs-shirokii** [comment] 2023-12-23 13:20
Adding `PostProcessArchive(filter);` after this line, makes namespaces be relevant if under `filter/`

https://github.com/ZDoom/gzdoom/blob/c05d6224ba0ae9e218036030744b3bd2f44d9c47/src/common/filesystem/source/file_directory.cpp#L155C4-L155C4

**Comment by vs-shirokii** [comment] 2023-12-23 13:25
Alright, now https://github.com/ZDoom/gzdoom/blob/c05d6224ba0ae9e218036030744b3bd2f44d9c47/src/common/filesystem/source/file_directory.cpp#L165 fails, because we remove `filter/<>/` prefixes and it can't read a file by that path

**Comment by vs-shirokii** [comment] 2023-12-23 14:09
Potential fix that just works https://github.com/ZDoom/gzdoom/pull/2320

**Closed** 2023-12-24 11:01 UTC
Labels: bug
